DROP DATABASE IF EXISTS kink_db;
CREATE DATABASE kink_db DEFAULT CHARACTER SET utf8 ;

USE kink_db;

CREATE TABLE states (
  id INT KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(2) NOT NULL,
  name VARCHAR(45) NOT NULL,
  population INT(10)
);

CREATE TABLE stis (
  id INT KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  info LONGTEXT 
);

CREATE TABLE sti_rates (
  id INT KEY NOT NULL AUTO_INCREMENT,
  sti_id INT(10) NOT NULL,
  state_id INT(10) NOT NULL,
	sti_cases INT(10),
  rate INT(10)
);
